### ISSUE TITLE
TypeError: stat is not a function

### ISSUE THREAD

**Issue by vishalc129** [desislavsd/require.all#4]
gives TypeError: stat is not a function error as there no such function in 'fs'.
Same goes with other function which we are calling. like - 
 fs.readFileSync,    readDir = fs.readdirSync,    stat    = fs.statSync;

all above function does not exists in fs = require('fs'),

**Comment by desislavsd** [comment]
Wow, are you sure this is an issue with the package? These functions [exist](https://nodejs.org/api/fs.html#fs_fs_statsync_path_options)!

**Comment by vishalc129** [comment]
installed fs from using 'npm i fs' from https://www.npmjs.com/package/fs . 
Installed version - 0.0.1-security

Please advise from where to install and what version

**Comment by desislavsd** [comment]
Bro, `requre.all` is a **nodejs** package and `fs` is a build in module of the **nodejs** framework - [you can find it in the official nodejs docs](https://nodejs.org/api/fs.html#fs_file_system). You can not use `require.all` in the browser.

I close the issue.
